model:
  si:
    class_path: omg.si.stochastic_interpolants.StochasticInterpolants
    init_args:
      stochastic_interpolants:
        # chemical species
        - class_path: omg.si.single_stochastic_interpolant_identity.SingleStochasticInterpolantIdentity
        #  init_args:
        #    noise: 0.
        # fractional coordinates
        - class_path: omg.si.single_stochastic_interpolant_os.SingleStochasticInterpolantOS
          init_args:
            interpolant: omg.si.interpolants.ScoreBasedDiffusionModelInterpolant
            epsilon: null
            differential_equation_type: "ODE"
            integrator_kwargs:
              method: "euler"
            #correct_center_of_mass: false
            correct_center_of_mass_motion: true
            predict_velocity: False
        # lattice vectors
        - class_path: omg.si.single_stochastic_interpolant_identity.SingleStochasticInterpolantIdentity
        #  init_args:
        #    interpolant: omg.si.interpolants.LinearInterpolant
        #    gamma: null
        #    epsilon: null
        #    differential_equation_type: "ODE"
        #    integrator_kwargs:
        #      method: "euler"
      data_fields: 
        # if the order of the data_fields changes,
        # the order of the above StochasticInterpolant inputs must also change
        - "species"
        - "pos"
        - "cell"
      integration_time_steps: 100
  relative_si_costs:
    species_loss: 0.
    pos_loss_z: 1.0
    cell_loss: 0.
  sampler:
    class_path: omg.sampler.sample_from_rng.SampleFromRNG
    init_args:
      pos_distribution:
        class_path: omg.sampler.distributions.NormalDistribution
      cell_distribution:
        class_path: omg.sampler.distributions.MirrorData
        #init_args:
        #  dataset_name: "mp_20"
      species_distribution:
        class_path: omg.sampler.distributions.MirrorData
      n_particle_sampler: 6
      convert_to_fractional: true
    # Code for sampling from dataset
    # class_path: omg.sampler.sample_from_dataset.SampleFromDataset
    # init_args:
    #   dataset:
    #   convert_to_fractional: 
    #   batch_size: 
  model:
    class_path: omg.model.model.Model
    init_args:
      encoder:
        class_path: omg.model.encoders.cspnet_full.CSPNetFull
        # assume all defaults are good
        # prop: True
      head:
        class_path: omg.model.heads.pass_through.PassThrough
      time_embedder:
        class_path: omg.model.model_utils.SinusoidalTimeEmbeddings
        init_args:
          dim: 256 # has to be same as latent_dim in cspnet
      # prop_embedder:
      #       class_path: omg.model.model_utils.SinusoidalTimeEmbeddings
      #       init_args:
      #           dim: 32 # has to be sam eas prop_emb_dim of adapter module
      # property_keys: "band_gap"
  use_min_perm_dist: false
data:
  train_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.OverfittingDataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/train.lmdb"
          structure_index: 0
      niggli: False
          # property_keys: # specify only when you wanna do guided training
          #  - "band_gap"
  val_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.OverfittingDataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/train.lmdb"
          structure_index: 0
      niggli: False
  predict_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.OverfittingDataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/train.lmdb"
          structure_index: 0
      niggli: False
  batch_size: 512
trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: "val_loss_total"
        save_weights_only: false
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1  # Store every checkpoint after 100 epochs.
        monitor: "val_loss_total"
        every_n_epochs: 100
        save_weights_only: false
    # - class_path: omg.utils.OMGLearningRateFinder
    #   init_args:
    #     min_lr: 0.00001
    #     num_training_steps: 200
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 100
        monitor: "val_loss_total"
  gradient_clip_val: 0.5
  num_sanity_val_steps: 0
  strategy: "ddp_find_unused_parameters_true"
  precision: "64-true"
optimizer: torch.optim.Adam
# lr_scheduler:
#   class_path: lightning.pytorch.cli.ReduceLROnPlateau
#   init_args:
#     patience: 40
#     monitor: "val_loss_total"
