model:
  class_path: stochastic_interpolants.StochasticInterpolants
  init_args:
    stochastic_interpolants:
      # chemical species
      - class_path: discrete_flow.DiscreteFlowMatchingMask
        init_args:
          n_int: 100
          noise: 0.
      # fractional coordinates
      - class_path: single_stochastic_interpolant.SingleStochasticInterpolant
        init_args:
          interpolant: interpolants.PeriodicLinearInterpolant
          gamma: null
          epsilon: null
          differential_equation_type: DifferentialEquationType.ODE
          sde_number_time_steps: null
          corrector: 
            class_path: corrector.PeriodicBoundaryConditionsCorrector
            init_args:
              min: 0
              max: 1
      # lattice vectors
      - class_path: single_stochastic_interpolant.SingleStochasticInterpolant
        init_args:
          interpolant: interpolants.LinearInterpolant
          gamma: null
          epsilon: null
          differential_equation_type: DifferentialEquationType.ODE
          sde_number_time_steps: null
          corrector: null
    costs:
      - 0.333333333333
      - 0.333333333333
      - 0.333333333333
    integration_time_steps: 100

