data:
  batch_size: 256
  predict_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
          - data/mp_20/train.lmdb
      niggli: false
  train_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
          - data/mp_20/train.lmdb
      niggli: false
  val_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
          - data/mp_20/val.lmdb
      niggli: false
model:
  model:
    class_path: omg.model.model.Model
    init_args:
      encoder:
        class_path: omg.model.encoders.cspnet_full.CSPNetFull
      head:
        class_path: omg.model.heads.pass_through.PassThrough
      time_embedder:
        class_path: omg.model.model_utils.SinusoidalTimeEmbeddings
        init_args:
          dim: 256
  relative_si_costs:
  - 1.0
  - 0.0
  - 0.0
  sampler:
    class_path: omg.sampler.sample_from_rng.SampleFromRNG
    init_args:
      batch_size: 2000
      cell_distribution:
        class_path: omg.sampler.distributions.MirrorData
      convert_to_fractional: true
      n_particle_sampler: 6
      pos_distribution:
        class_path: omg.sampler.distributions.MirrorData
  si:
    class_path: omg.si.stochastic_interpolants.StochasticInterpolants
    init_args:
      data_fields:
      - species
      - pos
      - cell
      integration_time_steps: 100
      stochastic_interpolants:
      - class_path: omg.si.discrete_flow_matching_mask.DiscreteFlowMatchingMask
        init_args:
          noise: 0.0
      - class_path: omg.si.single_stochastic_interpolant_identity.SingleStochasticInterpolantIdentity
        init_args: {}
      - class_path: omg.si.single_stochastic_interpolant_identity.SingleStochasticInterpolantIdentity
        init_args: {}
  use_min_perm_dist: false
trainer:
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      monitor: val_loss_total
      save_top_k: 1
  - class_path: omg.utils.OMGLearningRateFinder
    init_args:
      min_lr: 1.0e-05
      num_training_steps: 200
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss_total
      patience: 100
  gradient_clip_val: 0.5
  num_sanity_val_steps: 0
