model:
  si:
    class_path: omg.si.stochastic_interpolants.StochasticInterpolants
    init_args:
      stochastic_interpolants:
        # chemical species
        - class_path: omg.si.discrete_flow.DiscreteFlowMatchingMask
          init_args:
            number_integration_steps: 100
            noise: 0.
        # fractional coordinates
        - class_path: omg.si.single_stochastic_interpolant.SingleStochasticInterpolant
          init_args:
            interpolant: omg.si.interpolants.PeriodicLinearInterpolant
            gamma: null
            epsilon: null
            differential_equation_type: "ODE"
            sde_number_time_steps: null
            corrector: 
              class_path: omg.si.corrector.PeriodicBoundaryConditionsCorrector
              init_args:
                min: 0
                max: 1
        # lattice vectors
        - class_path: omg.si.single_stochastic_interpolant.SingleStochasticInterpolant
          init_args:
            interpolant: omg.si.interpolants.LinearInterpolant
            gamma: null
            epsilon: null
            differential_equation_type: "ODE"
            sde_number_time_steps: null
            corrector: null
      data_fields: 
        # if the order of the data_fields changes,
        # the order of the above StochasticInterpolant inputs must also change
        - "species"
        - "pos"
        - "cell"
      costs:
        - 0.333333333333
        - 0.333333333333
        - 0.333333333333
      integration_time_steps: 100

