# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test OMG package

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Start interactive slurm job
      run: |
        srun -c2 -t1:00:00 --mem=4000 --pty /bin/bash
    - name: Install python version
      run: |
        # See https://sites.google.com/nyu.edu/nyu-hpc/hpc-systems/greene/software/conda-environments-python-r
        module load anaconda3/2024.02
        conda create -p ./penv python=${{ matrix.python-version }}
        conda activate ./penv
        export PYTHONNOUSERSITE=True
        mkdir conda_pgks
        ln -s conda_pkgs ~/.conda/pkgs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Fix https://github.com/rusty1s/pytorch_scatter/issues/424
        python -m pip install setuptools wheel
        python -m pip install torch==2.4.0
        python -m pip install --no-use-pep517 torch_scatter==2.1.2
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest tests
    - name: Cleanup and exit slurm job
      run: |
        conda deactivate
        rm -rf conda_pkgs
        rm -rf ./penv
        exit
