# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test OMG package

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - name: Start interactive slurm job
      run: |
        srun -c2 -t1:00:00 --mem=4000 --pty /bin/bash
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    # - name: Install python
    #   run: |
        # See https://sites.google.com/nyu.edu/nyu-hpc/hpc-systems/greene/software/conda-environments-python-r
        # module purge
        # module load anaconda3/2024.02
        # source /share/apps/anaconda3/2024.02/etc/profile.d/conda.sh
        # mkdir conda_pkgs
        # mkdir pip_pkgs
        # export CONDA_PKGS_DIRS=$(pwd)/conda_pkgs
        # export PYTHONNOUSERSITE=True
        # conda create -p ./penv python=${{ matrix.python-version }} --channel=conda --channel=conda-forge -y
        # conda activate ./penv
    - name: Install dependencies and package
      run: |
        python -m pip --cache-dir ./pip_pkgs install --upgrade pip
        # Fix https://github.com/rusty1s/pytorch_scatter/issues/424
        python -m pip --cache-dir ./pip_pkgs install setuptools wheel
        python -m pip --cache-dir ./pip_pkgs install torch==2.4.0
        python -m pip --cache-dir ./pip_pkgs install --no-use-pep517 torch_scatter==2.1.2
        python -m pip --cache-dir ./pip_pkgs install .
    - name: Test with pytest
      run: |
        conda activate ./penv
        pytest tests
    - name: Cleanup and exit slurm job
      run: |
        conda deactivate
        rm -rf conda_pkgs
        rm -rf pip_pkgs
        rm -rf ./penv
        exit
